//! Capability traits for the effect system.
//!
//! This module provides the core `Capability` trait that defines the
//! input/output contract for effects, using coroutine-inspired terminology.

use crate::variant::{Concat, Never, Variant};

/// Core trait defining the input/output contract for an effect or ability.
///
/// Uses coroutine-inspired terminology:
/// - `Yield` - The variant type we send to the provider (capabilities)
/// - `Resume` - The variant type we receive back (results)
///
/// # Example
///
/// ```ignore
/// // For an individual effect like CounterGetCount:
/// impl Capability for CounterGetCount {
///     type Yield = Variant<CounterGetCount>;  // Just itself
///     type Resume = Variant<i32>;              // Just its result
/// }
///
/// // For an ability like Counter:
/// impl Capability for Counter {
///     type Yield = Variant<CounterGetCount, Variant<CounterIncrement, ...>>;
///     type Resume = Variant<i32, Variant<(), ...>>;
/// }
/// ```
pub trait Capability {
    /// The variant type we yield/send to the provider.
    type Yield;

    /// The variant type we receive back from the provider.
    type Resume;
}

/// Trait linking an effect to its parent ability type.
///
/// This trait is generated by the `ability!` macro for each capability struct.
/// It enables looking up the ability's `Yield`/`Resume` types from an individual effect,
/// along with the type-level index for the effect's position within the ability.
///
/// # Example
///
/// ```ignore
/// impl CapabilityOf for CounterGetCount {
///     type Ability = Counter;
///     type Index = Z; // First effect in the ability
/// }
///
/// impl CapabilityOf for CounterIncrement {
///     type Ability = Counter;
///     type Index = S<Z>; // Second effect in the ability
/// }
/// ```
pub trait CapabilityOf {
    /// The ability type that this effect belongs to.
    type Ability: Capability;
    /// Type-level index for this effect's position within the ability's `Yield` variant.
    type Index;
}

/// A trait for flattening nested capability groups into a flat variant.
///
/// When composing multiple capabilities, this trait expands each group
/// to its individual capabilities and concatenates them into a single flat
/// variant type.
///
/// # Example
///
/// Given:
/// - `State<T>` with `Yield = Variant<StateGet<T>, Variant<StateSet<T>, Never>>`
/// - `Logger` with `Yield = Variant<LoggerLog, Never>`
///
/// `FlattenGroups` on `Variant<State<T>, Variant<Logger, Never>>` produces:
/// `Variant<StateGet<T>, Variant<StateSet<T>, Variant<LoggerLog, Never>>>`
pub trait FlattenGroups {
    /// The flattened variant type containing all individual capabilities.
    type Flattened;
}

impl FlattenGroups for Never {
    type Flattened = Never;
}

impl<H, T> FlattenGroups for Variant<H, T>
where
    H: Capability,
    T: FlattenGroups,
    H::Yield: Concat<T::Flattened>,
{
    type Flattened = <H::Yield as Concat<T::Flattened>>::Output;
}

#[cfg(test)]
#[allow(dead_code)]
mod tests {
    use super::*;

    // Test capability types
    struct CapA;
    struct CapB;
    struct CapC;

    // Test groups
    struct GroupAB;
    struct GroupC;

    impl Capability for GroupAB {
        type Yield = Variant<CapA, Variant<CapB, Never>>;
        type Resume = Variant<(), Variant<(), Never>>;
    }

    impl Capability for GroupC {
        type Yield = Variant<CapC, Never>;
        type Resume = Variant<(), Never>;
    }

    #[test]
    fn test_flatten_single_group() {
        // Variant<GroupAB, Never> should flatten to Variant<CapA, Variant<CapB, Never>>
        type Groups = Variant<GroupAB, Never>;
        type Flattened = <Groups as FlattenGroups>::Flattened;

        // Type-level assertion - if this compiles, the types match
        fn _assert_type(_: Flattened) -> Variant<CapA, Variant<CapB, Never>> {
            unreachable!()
        }
    }

    #[test]
    fn test_flatten_multiple_groups() {
        // Variant<GroupAB, Variant<GroupC, Never>> should flatten to
        // Variant<CapA, Variant<CapB, Variant<CapC, Never>>>
        type Groups = Variant<GroupAB, Variant<GroupC, Never>>;
        type Flattened = <Groups as FlattenGroups>::Flattened;

        // Type-level assertion
        fn _assert_type(_: Flattened) -> Variant<CapA, Variant<CapB, Variant<CapC, Never>>> {
            unreachable!()
        }
    }
}
