//! Capability group traits for organizing effects.
//!
//! This module provides traits for grouping capabilities and flattening
//! nested capability groups into flat variant types.

use crate::variant::{Concat, Never, Variant};

/// A trait that links a capability marker type to its individual capabilities.
///
/// Types implementing this trait define a set of capabilities that they require
/// or provide. The `Capabilities` associated type is typically a `Variant` of
/// all the individual capability types.
///
/// # Example
///
/// ```ignore
/// struct MyEffect;
///
/// impl CapabilityGroup for MyEffect {
///     type Capabilities = Variant<ReadCapability, Variant<WriteCapability, Never>>;
/// }
/// ```
pub trait CapabilityGroup {
    /// The variant type containing all capabilities in this group.
    type Capabilities;
}

/// Trait for abilities that have a known output variant type.
///
/// The `ExpectedOutput` is the Variant of all return types from the ability's effects.
/// For Counter with `get_count() -> i32`, `increment() -> ()`, `add(i32) -> i32`,
/// this would be `Variant<i32, Variant<(), Variant<i32, Never>>>`.
///
/// This allows effectful to require `Provider<Caps, Output = ExpectedOutput>`,
/// ensuring Extract bounds are automatically satisfied since we know the concrete type.
pub trait OutputVariant: CapabilityGroup {
    /// The variant type containing all output types from this ability's effects.
    type ExpectedOutput;
}

/// Marker trait indicating that provider P can handle all effects in this ability group.
///
/// This trait is generated by the `ability!` macro. It encapsulates all the bounds
/// needed for `PerformIn` to work:
/// - `P: Provider<Self::Capabilities>` - P can handle the capabilities variant
/// - `P::Output: Extract<ReturnType, Idx>` - results can be extracted for each effect
///
/// This allows `#[effectful]` to use abstract bounds like `Counter: Handles<P>`
/// instead of concrete provider traits like `P: CounterProvider`.
///
/// Users can satisfy this trait by implementing `Provider<Capabilities>` directly,
/// similar to how effing-mad handlers work - receiving a variant, pattern matching,
/// and returning a variant of results.
pub trait Handles<P>: CapabilityGroup
where
    P: crate::Provider<Self::Capabilities>,
{
    /// The output variant type from the provider.
    type Output;
}

/// Trait linking an effect to its parent ability type.
///
/// This trait is generated by the `ability!` macro for each capability struct.
/// It allows `perform!` to dispatch effects through the correct ability's `Handle` impl.
pub trait HasAbility {
    /// The ability type that this effect belongs to.
    type Ability;
}

/// Trait for handling an effect through an ability's capabilities.
///
/// This trait is generated by the `ability!` macro for each capability.
/// It uses `PerformIn` to inject the effect into the capabilities variant,
/// invoke the provider, and extract the result.
pub trait Handle<E, P>
where
    E: crate::Effect,
{
    /// Handle the effect using the given provider.
    fn handle(
        effect: E,
        provider: &mut P,
    ) -> impl core::future::Future<Output = E::Output> + Send;
}

/// Dispatch an effect through its ability's Handle impl.
///
/// This function is used by the `perform!` macro to route effects to their
/// correct ability handler without needing to know the ability type at the macro level.
pub fn dispatch<E, A, P>(
    effect: E,
    provider: &mut P,
) -> impl core::future::Future<Output = E::Output> + Send
where
    E: crate::Effect + HasAbility<Ability = A> + Send,
    A: Handle<E, P>,
    E::Output: Send,
{
    A::handle(effect, provider)
}

/// A trait for flattening nested capability groups into a flat variant.
///
/// When composing multiple capability groups, this trait expands each group
/// to its individual capabilities and concatenates them into a single flat
/// variant type.
///
/// # Example
///
/// Given:
/// - `State<T>` with capabilities `Variant<StateGet<T>, Variant<StateSet<T>, Never>>`
/// - `Logger` with capabilities `Variant<LoggerLog, Never>`
///
/// `FlattenGroups` on `Variant<State<T>, Variant<Logger, Never>>` produces:
/// `Variant<StateGet<T>, Variant<StateSet<T>, Variant<LoggerLog, Never>>>`
pub trait FlattenGroups {
    /// The flattened variant type containing all individual capabilities.
    type Flattened;
}

impl FlattenGroups for Never {
    type Flattened = Never;
}

impl<H, T> FlattenGroups for Variant<H, T>
where
    H: CapabilityGroup,
    T: FlattenGroups,
    H::Capabilities: Concat<T::Flattened>,
{
    type Flattened = <H::Capabilities as Concat<T::Flattened>>::Output;
}

#[cfg(test)]
#[allow(dead_code)]
mod tests {
    use super::*;

    // Test capability types
    struct CapA;
    struct CapB;
    struct CapC;

    // Test groups
    struct GroupAB;
    struct GroupC;

    impl CapabilityGroup for GroupAB {
        type Capabilities = Variant<CapA, Variant<CapB, Never>>;
    }

    impl CapabilityGroup for GroupC {
        type Capabilities = Variant<CapC, Never>;
    }

    #[test]
    fn test_flatten_single_group() {
        // Variant<GroupAB, Never> should flatten to Variant<CapA, Variant<CapB, Never>>
        type Groups = Variant<GroupAB, Never>;
        type Flattened = <Groups as FlattenGroups>::Flattened;

        // Type-level assertion - if this compiles, the types match
        fn _assert_type(_: Flattened) -> Variant<CapA, Variant<CapB, Never>> {
            unreachable!()
        }
    }

    #[test]
    fn test_flatten_multiple_groups() {
        // Variant<GroupAB, Variant<GroupC, Never>> should flatten to
        // Variant<CapA, Variant<CapB, Variant<CapC, Never>>>
        type Groups = Variant<GroupAB, Variant<GroupC, Never>>;
        type Flattened = <Groups as FlattenGroups>::Flattened;

        // Type-level assertion
        fn _assert_type(_: Flattened) -> Variant<CapA, Variant<CapB, Variant<CapC, Never>>> {
            unreachable!()
        }
    }
}
